from __future__ import annotations

from typing import Protocol, TypeVar

from ..db.models import (
    AgentInputManifest,
    AgentRun,
    Asset,
    AssetReviewDecision,
    Attachment,
    AttachmentBinding,
    ClarificationRequest,
    CommandReceipt,
    ConfigurationReference,
    CostEvent,
    CreativeBriefCandidate,
    DAGNode,
    Decision,
    DeliveryAttempt,
    DependencyEdge,
    Entity,
    EntityVersion,
    Message,
    Project,
    ProjectEvent,
    PricingCatalogVersion,
    PricingRule,
    ProductionConfigVersion,
    ProductionImpactAnalysis,
    ProductionSnapshot,
    ProviderConfigVersion,
    QCFinding,
    QCReport,
    RequirementCandidate,
    RequirementVersion,
    PlanVersion,
    Shot,
    ShotPlanCandidate,
    SnapshotEntityVersion,
    StoragePolicyVersion,
    Timeline,
    TimelineItem,
    VideoSpecVersion,
    WorkflowSlotVersion,
    WorkAttempt,
    WorkItem,
)


ModelT = TypeVar("ModelT")
CreationRecord = (
    AgentInputManifest
    | AgentRun
    | Attachment
    | AttachmentBinding
    | ClarificationRequest
    | Entity
    | EntityVersion
    | Message
    | RequirementCandidate
    | RequirementVersion
)
PlanningRecord = AgentInputManifest | AgentRun | CreativeBriefCandidate | PlanVersion | Shot | ShotPlanCandidate
ProductionRecord = (
    ConfigurationReference
    | CostEvent
    | DAGNode
    | DependencyEdge
    | ProductionImpactAnalysis
    | ProductionSnapshot
    | SnapshotEntityVersion
    | WorkAttempt
    | WorkItem
)
QualityRecord = Asset | AssetReviewDecision | QCFinding | QCReport
EditorRecord = Timeline | TimelineItem
DeliveryRecord = Asset | DeliveryAttempt | QCFinding | QCReport


class ProjectRepository(Protocol):
    def list_recent(self) -> list[Project]: ...

    def get(self, project_id: str, *, with_workspace: bool = False) -> Project | None: ...

    def add(self, project: Project) -> None: ...

    def add_work_item(self, item: WorkItem) -> None: ...

    def flush(self) -> None: ...

    def refresh_work_item(self, item: WorkItem) -> None: ...


class EventRepository(Protocol):
    def add(self, event: ProjectEvent) -> None: ...

    def list_after(self, project_id: str, sequence: int, *, limit: int = 100) -> list[ProjectEvent]: ...


class DecisionRepository(Protocol):
    def get_by_key(self, project_id: str, key: str) -> Decision | None: ...

    def get_for_project(self, project_id: str, decision_id: str) -> Decision | None: ...

    def add(self, decision: Decision) -> None: ...

    def flush(self) -> None: ...

    def refresh(self, decision: Decision) -> None: ...


class CommandRepository(Protocol):
    def get(self, project_id: str, command_id: str) -> CommandReceipt | None: ...

    def add(
        self,
        project_id: str,
        command_id: str,
        command_type: str,
        result_type: str,
        result_id: str,
    ) -> CommandReceipt: ...

    def get_result(self, model_type: type[ModelT], result_id: str) -> ModelT | None: ...


class CreationRepository(Protocol):
    def add(self, record: CreationRecord) -> None: ...

    def flush(self) -> None: ...

    def active_requirement(self, project_id: str) -> RequirementVersion | None: ...

    def requirement_candidate(self, candidate_id: str) -> RequirementCandidate | None: ...

    def agent_run(self, run_id: str) -> AgentRun | None: ...

    def agent_manifest(self, manifest_id: str) -> AgentInputManifest | None: ...

    def pending_clarifications(self, project_id: str) -> list[ClarificationRequest]: ...

    def message(self, message_id: str) -> Message | None: ...

    def reviewable_candidates(
        self,
        project_id: str,
        *,
        exclude_id: str | None = None,
    ) -> list[RequirementCandidate]: ...

    def manifest_messages(self, project_id: str) -> list[Message]: ...

    def confirmed_bindings(self, project_id: str) -> list[AttachmentBinding]: ...

    def clarification(self, clarification_id: str) -> ClarificationRequest | None: ...

    def attachment(self, attachment_id: str) -> Attachment | None: ...

    def entity(self, entity_id: str) -> Entity | None: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def active_entity_version(self, entity_id: str) -> EntityVersion | None: ...

    def view_messages(self, project_id: str) -> list[Message]: ...

    def candidate_history(self, project_id: str) -> list[RequirementCandidate]: ...

    def agent_runs(self, project_id: str) -> list[AgentRun]: ...

    def attachments(self, project_id: str) -> list[Attachment]: ...

    def bindings(self, project_id: str) -> list[AttachmentBinding]: ...

    def active_pending_clarifications(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> list[ClarificationRequest]: ...


class PlanningRepository(Protocol):
    def add(self, record: PlanningRecord) -> None: ...

    def flush(self) -> None: ...

    def confirmed_binding_versions(self, project_id: str) -> list[AttachmentBinding]: ...

    def confirmed_binding_ids(self, project_id: str) -> list[str]: ...

    def active_brief_for_requirement(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> CreativeBriefCandidate | None: ...

    def creative_brief(self, candidate_id: str) -> CreativeBriefCandidate | None: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def reviewable_shot_plan_for_requirement(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> ShotPlanCandidate | None: ...

    def shot_plan(self, candidate_id: str) -> ShotPlanCandidate | None: ...

    def active_plans(self, project_id: str) -> list[PlanVersion]: ...

    def next_plan_version_number(self, project_id: str) -> int: ...

    def shots(self, plan_version_id: str) -> list[Shot]: ...

    def brief_history(self, project_id: str) -> list[CreativeBriefCandidate]: ...

    def shot_plan_history(self, project_id: str) -> list[ShotPlanCandidate]: ...

    def plan_history(self, project_id: str) -> list[PlanVersion]: ...

    def active_entity_versions(self, project_id: str) -> list[tuple[EntityVersion, Entity]]: ...


class ProductionRepository(Protocol):
    def add(self, record: ProductionRecord) -> None: ...

    def flush(self) -> None: ...

    def component(self, model_type: type[ModelT], component_id: str) -> ModelT | None: ...

    def snapshot_entities(self, snapshot_id: str) -> list[SnapshotEntityVersion]: ...

    def snapshot_nodes(self, snapshot_id: str, *, ordered: bool = False) -> list[DAGNode]: ...

    def snapshot_edges(self, snapshot_id: str) -> list[DependencyEdge]: ...

    def pricing_rules(self, pricing_catalog_version_id: str) -> list[PricingRule]: ...

    def impact_analysis(self, analysis_id: str) -> ProductionImpactAnalysis | None: ...

    def plan(self, plan_id: str) -> PlanVersion | None: ...

    def configuration(self, config_id: str) -> ProductionConfigVersion | None: ...

    def plan_shots(self, plan_id: str) -> list[Shot]: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def snapshot_for_impact(self, analysis_id: str) -> ProductionSnapshot | None: ...

    def next_snapshot_number(self, project_id: str) -> int: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def pricing_catalog(self, pricing_id: str) -> PricingCatalogVersion | None: ...

    def workflow(self, workflow_id: str) -> WorkflowSlotVersion | None: ...

    def provider(self, provider_id: str) -> ProviderConfigVersion | None: ...

    def has_work_items(self, snapshot_id: str) -> bool: ...

    def work_items(self, snapshot_id: str) -> list[WorkItem]: ...

    def work_attempts(self, work_item_ids: list[str]) -> list[WorkAttempt]: ...

    def active_plan(self, project_id: str) -> PlanVersion | None: ...

    def published_configurations(self) -> list[ProductionConfigVersion]: ...

    def video_specs(self, config_id: str) -> list[VideoSpecVersion]: ...

    def workflows(self, config_id: str) -> list[WorkflowSlotVersion]: ...

    def pricing_catalogs(self, config_id: str) -> list[PricingCatalogVersion]: ...

    def impact_history(self, project_id: str) -> list[ProductionImpactAnalysis]: ...

    def snapshot_history(self, project_id: str) -> list[ProductionSnapshot]: ...


class QualityRepository(Protocol):
    def add(self, record: QualityRecord) -> None: ...

    def flush(self) -> None: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def published_storage_policies(self, config_id: str) -> list[StoragePolicyVersion]: ...

    def work_attempt(self, attempt_id: str) -> WorkAttempt | None: ...

    def work_item(self, work_item_id: str) -> WorkItem | None: ...

    def dag_node(self, node_id: str) -> DAGNode | None: ...

    def asset_for_output(self, work_attempt_id: str, output_index: int) -> Asset | None: ...

    def work_item_for_node(self, snapshot_id: str, dag_node_id: str) -> WorkItem | None: ...

    def qc_report(self, report_id: str) -> QCReport | None: ...

    def next_report_number(self, asset_id: str) -> int: ...

    def has_review_decision(self, report_id: str) -> bool: ...

    def findings(self, report_id: str) -> list[QCFinding]: ...

    def dependency_edges(self, snapshot_id: str) -> list[DependencyEdge]: ...

    def dag_nodes_by_ids(self, node_ids: set[str]) -> list[DAGNode]: ...

    def latest_qc_report(self, asset_id: str) -> QCReport | None: ...

    def review_decisions(self, asset_id: str) -> list[AssetReviewDecision]: ...

    def project_assets(self, project_id: str) -> list[Asset]: ...

    def snapshot_nodes(self, snapshot_id: str) -> list[DAGNode]: ...


class EditorRepository(Protocol):
    def add(self, record: EditorRecord) -> None: ...

    def flush(self) -> None: ...

    def timeline(self, timeline_id: str) -> Timeline | None: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def agent_run(self, run_id: str) -> AgentRun | None: ...

    def timeline_items(self, timeline_id: str) -> list[TimelineItem]: ...

    def has_timeline(self, project_id: str) -> bool: ...

    def next_timeline_version(self, project_id: str) -> int: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def confirmed_timelines(self, project_id: str, *, exclude_id: str) -> list[Timeline]: ...

    def timeline_asset_ids(self, timeline_id: str) -> list[str]: ...

    def assets_by_ids(self, asset_ids: list[str]) -> list[Asset]: ...

    def available_assets(self, project_id: str, snapshot_id: str) -> list[Asset]: ...

    def dag_nodes_by_ids(self, node_ids: list[str]) -> list[DAGNode]: ...

    def timeline_history(self, project_id: str) -> list[Timeline]: ...


class DeliveryRepository(Protocol):
    def add(self, record: DeliveryRecord) -> None: ...

    def flush(self) -> None: ...

    def attempt(self, attempt_id: str) -> DeliveryAttempt | None: ...

    def confirmed_timelines(
        self,
        project_id: str,
        snapshot_id: str | None,
        *,
        timeline_id: str | None = None,
    ) -> list[Timeline]: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def timeline_items(self, timeline_id: str) -> list[TimelineItem]: ...

    def assets_by_ids(self, asset_ids: list[str]) -> list[Asset]: ...

    def has_attempt_for_timeline(self, timeline_id: str) -> bool: ...

    def asset_by_uri(self, storage_backend: str, uri: str) -> Asset | None: ...

    def next_report_number(self, asset_id: str) -> int: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def delivery_timelines(self, project_id: str, snapshot_id: str) -> list[Timeline]: ...

    def project_attempts(self, project_id: str) -> list[DeliveryAttempt]: ...
