from __future__ import annotations

from datetime import datetime
from typing import Protocol, TypeVar

from ..db.models import (
    AgentInputManifest,
    AgentRun,
    Asset,
    AssetReviewDecision,
    Attachment,
    AttachmentBinding,
    ClarificationRequest,
    CommandReceipt,
    ConfigurationCommandReceipt,
    ConfigurationEvent,
    ConfigurationReference,
    ConversationSession,
    CostEvent,
    CreativeBriefCandidate,
    CreativeSuggestionSelection,
    CreativeTurnProposal,
    DAGNode,
    Decision,
    DecisionChangeImpactAnalysis,
    DecisionChangeImpactTarget,
    DeliveryAttempt,
    EditorDraftSession,
    DependencyEdge,
    Entity,
    EntityVersion,
    Message,
    ModelConfigVersion,
    OutboxMessage,
    Project,
    ProjectEvent,
    PricingCatalogVersion,
    PricingRule,
    ProductionConfigComponent,
    ProductionConfigVersion,
    ProductionImpactAnalysis,
    ProductionPlanCandidate,
    ProductionSnapshot,
    ProviderConfigVersion,
    QCFinding,
    QCReport,
    QCReportCandidate,
    RequirementCandidate,
    RequirementVersion,
    PlanVersion,
    Shot,
    ShotPlanCandidate,
    SnapshotEntityVersion,
    StoragePolicyVersion,
    Timeline,
    TimelineItem,
    VideoSpecVersion,
    WorkflowSlotVersion,
    WorkAttempt,
    WorkItem,
    AudioConfigVersion,
)


ModelT = TypeVar("ModelT")
CreationRecord = (
    AgentInputManifest
    | AgentRun
    | Attachment
    | AttachmentBinding
    | ClarificationRequest
    | ConversationSession
    | CreativeSuggestionSelection
    | CreativeTurnProposal
    | Entity
    | EntityVersion
    | Message
    | RequirementCandidate
    | RequirementVersion
)
PlanningRecord = AgentInputManifest | AgentRun | CreativeBriefCandidate | PlanVersion | Shot | ShotPlanCandidate
ImpactRecord = DecisionChangeImpactAnalysis | DecisionChangeImpactTarget
ProductionRecord = (
    AgentInputManifest
    | AgentRun
    | ConfigurationReference
    | CostEvent
    | DAGNode
    | DependencyEdge
    | ProductionImpactAnalysis
    | ProductionPlanCandidate
    | ProductionSnapshot
    | SnapshotEntityVersion
    | WorkAttempt
    | WorkItem
)
QualityRecord = Asset | AssetReviewDecision | QCFinding | QCReport | QCReportCandidate | AgentInputManifest | AgentRun
EditorRecord = AgentInputManifest | AgentRun | EditorDraftSession | Timeline | TimelineItem
DeliveryRecord = Asset | DeliveryAttempt | QCFinding | QCReport
ConfigurationComponentRecord = (
    ProviderConfigVersion
    | ModelConfigVersion
    | WorkflowSlotVersion
    | VideoSpecVersion
    | AudioConfigVersion
    | StoragePolicyVersion
    | PricingCatalogVersion
)
ConfigurationRecord = (
    ConfigurationCommandReceipt
    | ConfigurationEvent
    | ConfigurationReference
    | ProductionConfigVersion
    | ProductionConfigComponent
    | ConfigurationComponentRecord
    | PricingRule
)


class ProjectRepository(Protocol):
    def list_recent(self, *, include_archived: bool = False) -> list[Project]: ...

    def get(self, project_id: str, *, with_workspace: bool = False) -> Project | None: ...

    def add(self, project: Project) -> None: ...

    def add_work_item(self, item: WorkItem) -> None: ...

    def flush(self) -> None: ...

    def refresh_work_item(self, item: WorkItem) -> None: ...

    def has_active_work(self, project_id: str) -> bool: ...

    def update_archive(
        self,
        project: Project,
        *,
        expected_row_version: int,
        archived_at: datetime | None,
        archived_by: str | None,
    ) -> bool: ...


class ProjectStateRepository(Protocol):
    def transition_state(
        self,
        project: Project,
        *,
        expected_status: str,
        expected_row_version: int,
        target_status: str,
        changed_at: datetime,
        actor_type: str,
        actor_id: str,
        trigger: str,
        reason_code: str | None,
        blocked_from_state: str | None,
        responsible_aggregate_type: str | None,
        responsible_aggregate_id: str | None,
        allowed_commands: list[str],
        blocked_at: datetime | None,
    ) -> bool: ...


class EventRepository(Protocol):
    def add(self, event: ProjectEvent) -> None: ...

    def list_after(self, project_id: str, sequence: int, *, limit: int = 100) -> list[ProjectEvent]: ...

    def get_by_event_id(self, event_id: str) -> ProjectEvent | None: ...


class OutboxRepository(Protocol):
    def list_pending(self, *, limit: int = 100, now: datetime | None = None) -> list[OutboxMessage]: ...

    def mark_published(self, message_id: str, *, published_at: datetime) -> bool: ...


class DecisionRepository(Protocol):
    def get_by_key(self, project_id: str, key: str) -> Decision | None: ...

    def get_for_project(self, project_id: str, decision_id: str) -> Decision | None: ...

    def resolved_for_project(self, project_id: str) -> list[Decision]: ...

    def add(self, decision: Decision) -> None: ...

    def flush(self) -> None: ...

    def refresh(self, decision: Decision) -> None: ...


class CommandRepository(Protocol):
    def get(self, project_id: str, command_id: str) -> CommandReceipt | None: ...

    def add(
        self,
        project_id: str,
        command_id: str,
        command_type: str,
        result_type: str,
        result_id: str,
    ) -> CommandReceipt: ...

    def get_result(self, model_type: type[ModelT], result_id: str) -> ModelT | None: ...


class CreationRepository(Protocol):
    def add(self, record: CreationRecord) -> None: ...

    def flush(self) -> None: ...

    def active_requirement(self, project_id: str) -> RequirementVersion | None: ...

    def active_conversation_session(self, project_id: str) -> ConversationSession | None: ...

    def requirement_candidate(self, candidate_id: str) -> RequirementCandidate | None: ...

    def latest_conversation_candidate(
        self,
        project_id: str,
        conversation_session_id: str,
        base_requirement_version_id: str,
    ) -> RequirementCandidate | None: ...

    def agent_run(self, run_id: str) -> AgentRun | None: ...

    def agent_manifest(self, manifest_id: str) -> AgentInputManifest | None: ...

    def creative_proposal(self, proposal_id: str) -> CreativeTurnProposal | None: ...

    def active_creative_proposal(self, project_id: str) -> CreativeTurnProposal | None: ...

    def creative_proposals(self, project_id: str) -> list[CreativeTurnProposal]: ...

    def suggestion_selection(
        self,
        proposal_id: str,
        suggestion_set_id: str,
    ) -> CreativeSuggestionSelection | None: ...

    def suggestion_selections(self, project_id: str) -> list[CreativeSuggestionSelection]: ...

    def pending_clarifications(self, project_id: str) -> list[ClarificationRequest]: ...

    def message(self, message_id: str) -> Message | None: ...

    def reviewable_candidates(
        self,
        project_id: str,
        *,
        exclude_id: str | None = None,
    ) -> list[RequirementCandidate]: ...

    def manifest_messages(self, project_id: str, conversation_session_id: str) -> list[Message]: ...

    def confirmed_bindings(self, project_id: str) -> list[AttachmentBinding]: ...

    def clarification(self, clarification_id: str) -> ClarificationRequest | None: ...

    def attachment(self, attachment_id: str) -> Attachment | None: ...

    def entity(self, entity_id: str) -> Entity | None: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def active_entity_version(self, entity_id: str) -> EntityVersion | None: ...

    def view_messages(self, project_id: str, conversation_session_id: str) -> list[Message]: ...

    def candidate_history(self, project_id: str) -> list[RequirementCandidate]: ...

    def agent_runs(self, project_id: str) -> list[AgentRun]: ...

    def attachments(self, project_id: str) -> list[Attachment]: ...

    def bindings(self, project_id: str) -> list[AttachmentBinding]: ...

    def active_pending_clarifications(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> list[ClarificationRequest]: ...


class PlanningRepository(Protocol):
    def add(self, record: PlanningRecord) -> None: ...

    def flush(self) -> None: ...

    def confirmed_binding_versions(self, project_id: str) -> list[AttachmentBinding]: ...

    def confirmed_binding_ids(self, project_id: str) -> list[str]: ...

    def active_brief_for_requirement(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> CreativeBriefCandidate | None: ...

    def creative_brief(self, candidate_id: str) -> CreativeBriefCandidate | None: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def entity(self, entity_id: str) -> Entity | None: ...

    def attachment(self, attachment_id: str) -> Attachment | None: ...

    def reviewable_shot_plan_for_requirement(
        self,
        project_id: str,
        requirement_version_id: str,
    ) -> ShotPlanCandidate | None: ...

    def shot_plan(self, candidate_id: str) -> ShotPlanCandidate | None: ...

    def transition_reviewable_shot_plan(
        self,
        candidate_id: str,
        expected_row_version: int,
        status: str,
        decided_at: datetime,
        validation_errors: list[dict] | None = None,
    ) -> bool: ...

    def active_plans(self, project_id: str) -> list[PlanVersion]: ...

    def next_plan_version_number(self, project_id: str) -> int: ...

    def shots(self, plan_version_id: str) -> list[Shot]: ...

    def brief_history(self, project_id: str) -> list[CreativeBriefCandidate]: ...

    def shot_plan_history(self, project_id: str) -> list[ShotPlanCandidate]: ...

    def plan_history(self, project_id: str) -> list[PlanVersion]: ...

    def active_entity_versions(self, project_id: str) -> list[tuple[EntityVersion, Entity]]: ...


class ProductionRepository(Protocol):
    def add(self, record: ProductionRecord) -> None: ...

    def flush(self) -> None: ...

    def production_plan_candidate(self, candidate_id: str) -> ProductionPlanCandidate | None: ...

    def production_plan_candidates(self, project_id: str, plan_version_id: str | None = None) -> list[ProductionPlanCandidate]: ...

    def latest_production_planner_run(self, project_id: str, plan_version_id: str) -> AgentRun | None: ...

    def production_planner_runs(self, project_id: str, plan_version_id: str) -> list[AgentRun]: ...

    def agent_run(self, run_id: str) -> AgentRun | None: ...

    def agent_manifest(self, manifest_id: str) -> AgentInputManifest | None: ...

    def component(self, model_type: type[ModelT], component_id: str) -> ModelT | None: ...

    def snapshot_entities(self, snapshot_id: str) -> list[SnapshotEntityVersion]: ...

    def snapshot_nodes(self, snapshot_id: str, *, ordered: bool = False) -> list[DAGNode]: ...

    def snapshot_edges(self, snapshot_id: str) -> list[DependencyEdge]: ...

    def pricing_rules(self, pricing_catalog_version_id: str) -> list[PricingRule]: ...

    def impact_analysis(self, analysis_id: str) -> ProductionImpactAnalysis | None: ...

    def plan(self, plan_id: str) -> PlanVersion | None: ...

    def configuration(self, config_id: str) -> ProductionConfigVersion | None: ...

    def plan_shots(self, plan_id: str) -> list[Shot]: ...

    def entity_version(self, version_id: str) -> EntityVersion | None: ...

    def attachment(self, attachment_id: str) -> Attachment | None: ...

    def open_snapshot_for_contract(self, project_id: str, contract_hash: str) -> ProductionSnapshot | None: ...

    def snapshot_for_impact(self, analysis_id: str) -> ProductionSnapshot | None: ...

    def next_snapshot_number(self, project_id: str) -> int: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def pricing_catalog(self, pricing_id: str) -> PricingCatalogVersion | None: ...

    def workflow(self, workflow_id: str) -> WorkflowSlotVersion | None: ...

    def provider(self, provider_id: str) -> ProviderConfigVersion | None: ...

    def has_work_items(self, snapshot_id: str) -> bool: ...

    def work_items(self, snapshot_id: str) -> list[WorkItem]: ...

    def work_attempts(self, work_item_ids: list[str]) -> list[WorkAttempt]: ...

    def snapshot_assets(self, snapshot_id: str) -> list[Asset]: ...

    def active_plan(self, project_id: str) -> PlanVersion | None: ...

    def published_configurations(self) -> list[ProductionConfigVersion]: ...

    def video_specs(self, config_id: str) -> list[VideoSpecVersion]: ...

    def workflows(self, config_id: str) -> list[WorkflowSlotVersion]: ...

    def pricing_catalogs(self, config_id: str) -> list[PricingCatalogVersion]: ...

    def storage_policies(self, config_id: str) -> list[StoragePolicyVersion]: ...

    def audio_configs(self, config_id: str) -> list[AudioConfigVersion]: ...

    def impact_history(self, project_id: str) -> list[ProductionImpactAnalysis]: ...

    def snapshot_history(self, project_id: str) -> list[ProductionSnapshot]: ...


class QualityRepository(Protocol):
    def add(self, record: QualityRecord) -> None: ...

    def flush(self) -> None: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def published_storage_policies(self, config_id: str) -> list[StoragePolicyVersion]: ...

    def work_attempt(self, attempt_id: str) -> WorkAttempt | None: ...

    def work_item(self, work_item_id: str) -> WorkItem | None: ...

    def dag_node(self, node_id: str) -> DAGNode | None: ...

    def asset_for_output(self, work_attempt_id: str, output_index: int) -> Asset | None: ...

    def work_item_for_node(self, snapshot_id: str, dag_node_id: str) -> WorkItem | None: ...

    def qc_report(self, report_id: str) -> QCReport | None: ...

    def qc_candidate(self, candidate_id: str) -> QCReportCandidate | None: ...

    def latest_qc_candidate(self, asset_id: str) -> QCReportCandidate | None: ...

    def latest_qc_agent_run(self, asset_id: str) -> AgentRun | None: ...

    def next_report_number(self, asset_id: str) -> int: ...

    def has_review_decision(self, report_id: str) -> bool: ...

    def findings(self, report_id: str) -> list[QCFinding]: ...

    def dependency_edges(self, snapshot_id: str) -> list[DependencyEdge]: ...

    def dag_nodes_by_ids(self, node_ids: set[str]) -> list[DAGNode]: ...

    def latest_qc_report(self, asset_id: str) -> QCReport | None: ...

    def review_decisions(self, asset_id: str) -> list[AssetReviewDecision]: ...

    def project_assets(self, project_id: str) -> list[Asset]: ...

    def snapshot_nodes(self, snapshot_id: str) -> list[DAGNode]: ...


class EditorRepository(Protocol):
    def add(self, record: EditorRecord) -> None: ...

    def flush(self) -> None: ...

    def timeline(self, timeline_id: str) -> Timeline | None: ...

    def editor_draft(self, project_id: str) -> EditorDraftSession | None: ...

    def delete_editor_draft(self, project_id: str) -> None: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def agent_run(self, run_id: str) -> AgentRun | None: ...

    def timeline_items(self, timeline_id: str) -> list[TimelineItem]: ...

    def has_timeline(self, project_id: str, snapshot_id: str) -> bool: ...

    def next_timeline_version(self, project_id: str) -> int: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def confirmed_timelines(self, project_id: str, *, exclude_id: str) -> list[Timeline]: ...

    def timeline_asset_ids(self, timeline_id: str) -> list[str]: ...

    def assets_by_ids(self, asset_ids: list[str]) -> list[Asset]: ...

    def available_assets(self, project_id: str, snapshot_id: str) -> list[Asset]: ...

    def dag_nodes_by_ids(self, node_ids: list[str]) -> list[DAGNode]: ...

    def timeline_history(self, project_id: str) -> list[Timeline]: ...

    def active_plan(self, project_id: str) -> PlanVersion | None: ...

    def shots(self, plan_version_id: str) -> list[Shot]: ...

    def qc_reports(self, asset_ids: list[str]) -> list[QCReport]: ...

    def latest_editor_run(self, project_id: str, snapshot_id: str) -> AgentRun | None: ...

    def input_manifest(self, manifest_id: str) -> AgentInputManifest | None: ...


class DeliveryRepository(Protocol):
    def add(self, record: DeliveryRecord) -> None: ...

    def flush(self) -> None: ...

    def attempt(self, attempt_id: str) -> DeliveryAttempt | None: ...

    def confirmed_timelines(
        self,
        project_id: str,
        snapshot_id: str | None,
        *,
        timeline_id: str | None = None,
    ) -> list[Timeline]: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def timeline_items(self, timeline_id: str) -> list[TimelineItem]: ...

    def assets_by_ids(self, asset_ids: list[str]) -> list[Asset]: ...

    def has_attempt_for_timeline(self, timeline_id: str) -> bool: ...

    def asset_by_uri(self, storage_backend: str, uri: str) -> Asset | None: ...

    def next_report_number(self, asset_id: str) -> int: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def delivery_timelines(self, project_id: str, snapshot_id: str) -> list[Timeline]: ...

    def project_attempts(self, project_id: str) -> list[DeliveryAttempt]: ...


class WorkRepository(Protocol):
    def required_parent_items(self, item: WorkItem) -> list[WorkItem]: ...

    def required_parent_input_slots(self, item: WorkItem) -> dict[str, str]: ...

    def snapshot_work_states(self, snapshot_id: str) -> list[str]: ...

    def lease_candidates(self, available_at: datetime, *, limit: int = 50) -> list[WorkItem]: ...

    def poll_candidates(self, available_at: datetime, *, limit: int = 50) -> list[WorkItem]: ...

    def attempt(self, attempt_id: str) -> WorkAttempt | None: ...

    def project(self, project_id: str) -> Project | None: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def asset(self, asset_id: str) -> Asset | None: ...

    def claim(self, item: WorkItem, started_at: datetime) -> bool: ...

    def claim_with_provider_capacity(
        self,
        item: WorkItem,
        started_at: datetime,
        provider_key: str,
        max_concurrency: int,
    ) -> bool: ...

    def claim_attempt(self, attempt: WorkAttempt, owner: str, expires_at: datetime, now: datetime) -> bool: ...

    def work_item(self, work_item_id: str) -> WorkItem | None: ...

    def flush(self) -> None: ...


class ConfigurationRepository(Protocol):
    def add(self, record: ConfigurationRecord) -> None: ...

    def flush(self) -> None: ...

    def receipt(self, command_id: str) -> ConfigurationCommandReceipt | None: ...

    def configuration(self, config_id: str) -> ProductionConfigVersion | None: ...

    def next_configuration_version(self, config_key: str) -> int: ...

    def next_component_version(self, component_type: str, key: str) -> int: ...

    def component_rows(self, config_id: str) -> dict[str, list[ConfigurationComponentRecord]]: ...

    def pricing_rules(self, catalog_ids: list[str], *, ordered: bool = False) -> list[PricingRule]: ...

    def delete_components(self, config_id: str) -> None: ...

    def references(self, config_id: str) -> list[ConfigurationReference]: ...

    def configurations(self) -> list[ProductionConfigVersion]: ...

    def all_components(self, component_type: str) -> list[ConfigurationComponentRecord]: ...

    def workflow_slot_versions(self, slot_key: str) -> list[WorkflowSlotVersion]: ...


class RegistryRepository(Protocol):
    def projects(self, *, include_archived: bool = False) -> list[Project]: ...

    def entities(self) -> list[Entity]: ...

    def entity_versions(self) -> list[EntityVersion]: ...

    def attachments_by_ids(self, attachment_ids: set[str]) -> list[Attachment]: ...

    def bindings_by_entity_version_ids(self, entity_version_ids: set[str]) -> list[AttachmentBinding]: ...

    def snapshots(self) -> list[ProductionSnapshot]: ...

    def snapshot_entity_versions(self, entity_version_ids: set[str]) -> list[SnapshotEntityVersion]: ...

    def plans(self) -> list[PlanVersion]: ...

    def shots(self) -> list[Shot]: ...

    def attachment(self, attachment_id: str) -> Attachment | None: ...


class ControlRepository(Protocol):
    def active_plan(self, project_id: str) -> PlanVersion | None: ...

    def requirement_version(self, project_id: str, requirement_version_id: str) -> RequirementVersion | None: ...

    def shots_for_plan(self, project_id: str, plan_version_id: str) -> list[Shot]: ...

    def snapshots(self, project_id: str) -> list[ProductionSnapshot]: ...

    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def attempts_for_items(self, work_item_ids: list[str]) -> list[WorkAttempt]: ...

    def cost_events(self, project_id: str) -> list[CostEvent]: ...

    def dag_nodes(self, snapshot_id: str) -> list[DAGNode]: ...

    def latest_blocked_report(self, asset_id: str) -> QCReport | None: ...

    def findings(self, report_id: str) -> list[QCFinding]: ...

    def work_items(self, project_id: str, snapshot_id: str | None) -> list[WorkItem]: ...

    def assets(self, project_id: str, snapshot_id: str | None) -> list[Asset]: ...

    def latest_timeline(self, project_id: str) -> Timeline | None: ...

    def latest_delivery(self, project_id: str) -> DeliveryAttempt | None: ...

    def has_planning_candidate(self, project_id: str) -> bool: ...

    def events(
        self,
        project_id: str,
        *,
        limit: int = 20,
        before_sequence: int | None = None,
    ) -> list[ProjectEvent]: ...

    def projects(self) -> list[Project]: ...


class ContactSheetRepository(Protocol):
    def snapshot(self, snapshot_id: str) -> ProductionSnapshot | None: ...

    def nodes(self, snapshot_id: str) -> list[DAGNode]: ...

    def shots(self, project_id: str, plan_version_id: str) -> list[Shot]: ...

    def assets(self, project_id: str, snapshot_id: str) -> list[Asset]: ...

    def edges(self, snapshot_id: str) -> list[DependencyEdge]: ...

    def work_items(self, project_id: str, snapshot_id: str) -> list[WorkItem]: ...

    def attempts_for_items(self, work_item_ids: set[str]) -> list[WorkAttempt]: ...

    def entity_versions(self, project_id: str, version_ids: set[str]) -> list[EntityVersion]: ...

    def entities(self, project_id: str, entity_ids: set[str]) -> list[Entity]: ...

    def attachments(self, project_id: str, attachment_ids: set[str]) -> list[Attachment]: ...


class ImpactRepository(Protocol):
    def add(self, record: ImpactRecord) -> None: ...

    def flush(self) -> None: ...

    def decision(self, project_id: str, decision_id: str) -> Decision | None: ...

    def decisions(self, project_id: str) -> list[Decision]: ...

    def manifests(self, project_id: str) -> list[AgentInputManifest]: ...

    def agent_runs(self, project_id: str) -> list[AgentRun]: ...

    def requirement_candidates(self, project_id: str) -> list[RequirementCandidate]: ...

    def requirement_versions(self, project_id: str) -> list[RequirementVersion]: ...

    def creative_briefs(self, project_id: str) -> list[CreativeBriefCandidate]: ...

    def shot_plans(self, project_id: str) -> list[ShotPlanCandidate]: ...

    def plans(self, project_id: str) -> list[PlanVersion]: ...

    def shots(self, project_id: str) -> list[Shot]: ...

    def snapshots(self, project_id: str) -> list[ProductionSnapshot]: ...

    def dag_nodes(self, snapshot_ids: set[str]) -> list[DAGNode]: ...

    def work_items(self, project_id: str) -> list[WorkItem]: ...

    def assets(self, project_id: str) -> list[Asset]: ...

    def timelines(self, project_id: str) -> list[Timeline]: ...

    def timeline_items(self, timeline_ids: set[str]) -> list[TimelineItem]: ...

    def entity_versions(self, project_id: str) -> list[EntityVersion]: ...

    def entities(self, project_id: str) -> list[Entity]: ...

    def change_analysis(self, project_id: str, analysis_id: str) -> DecisionChangeImpactAnalysis | None: ...

    def change_analysis_history(self, project_id: str) -> list[DecisionChangeImpactAnalysis]: ...

    def change_analysis_targets(self, analysis_id: str) -> list[DecisionChangeImpactTarget]: ...
