from __future__ import annotations

from typing import Protocol

from ..db.models import Project, ProjectEvent, WorkItem


class ProjectRepository(Protocol):
    def list_recent(self) -> list[Project]: ...

    def get(self, project_id: str, *, with_workspace: bool = False) -> Project | None: ...

    def add(self, project: Project) -> None: ...

    def add_work_item(self, item: WorkItem) -> None: ...

    def flush(self) -> None: ...

    def refresh_work_item(self, item: WorkItem) -> None: ...


class EventRepository(Protocol):
    def add(self, event: ProjectEvent) -> None: ...

    def list_after(self, project_id: str, sequence: int, *, limit: int = 100) -> list[ProjectEvent]: ...
